### ISSUE TITLE
Same file listed twice in process_modalities.sh

### ISSUE THREAD

**Issue by jashubbard** [jeffduda/NeuroBattery#5]
when calling nii2dt.sh, the same dwi image is listed twice:

--dwi ../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0013_DTI_1_1x0_30x1000.nii.gz
../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0013_DTI_1_1x0_30x1000.nii.gz

instead of 

--dwi ../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0013_DTI_1_1x0_30x1000.nii.gz ../data/input/PEDS012/20131101/DWI/PEDS012_20131101_0019_DTI_1_1x0_30x1000.nii.gz

**Comment by stnava** [comment]
can you make a pull request that implements your suggested fix?


brian

**Comment by jeffduda** [comment]
Fixed
