### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by anbai106** [jeffduda/NeuroBattery#7]
Hello, 
I am new to your platform, and I have some problem to configure all the softwares that you need in the pipedream_config.sh, I insatlled all the softwares, but I think in the config files for pipedream, I have some problems, I got this errors:

I run **./run_test.sh**

  **% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    119      0  0:00:01  0:00:01 --:--:--   166
Archive:  ../data/template/PTBP.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ../data/template/PTBP.zip or
        ../data/template/PTBP.zip.zip, and cannot find ../data/template/PTBP.zip.ZIP, period.
sh: /Users/junhao.wen/Software/afni/abin//antsCorticalThickness.sh: No such file or directory
Cannot find Sun Java at Pipedream default path /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
Using version on system path
Cannot find ANTS at Pipedream default path /Users/junhao.wen/Software/afni/abin/
Using version on system path
Cannot create working directory /var/folders/5r/10gy0dnn1x1dykzyb4117pcc000hzl/T//PEDS012_20131101_DTI_dtiproc
	 at /Users/junhao.wen/Software/pipedream/pipedream/nii2dt/nii2dt.pl line 114.
./process_modalities.sh: line 9: /Users/junhao.wen/Software/afni/abin//antsNeuroimagingBattery: No such file or directory
./run_test.sh: line 52: ./warp_labels.h: No such file or directory
[1] "Saving results to ../docs/logfile.csv"
[1] "../data/output/PEDS012/20131101/"
[1] "../data/reference/PEDS012/20131101/"
[1] "../docs/PEDS012_20131101.pdf"

processing file: comparison.Rmd
  |.....                                                            |   7%
  ordinary text without R code

  |.........                                                        |  14%
label: unnamed-chunk-1 (with options)
List of 3
 $ fig.width : num 8
 $ fig.height: num 4
 $ echo      : logi FALSE

  |..............                                                   |  21%
  ordinary text without R code

  |...................                                              |  29%
label: unnamed-chunk-2 (with options)
List of 3
 $ fig.width : num 8
 $ fig.height: num 4
 $ echo      : logi FALSE

Quitting from lines 21-54 (comparison.Rmd)
Error in antsImageRead(mask.test, 3) : file does not exist
Calls: render ... withCallingHandlers -> withVisible -> eval -> eval -> antsImageRead

Execution halted**

To be clear, I attached my pipedream config file in txt file
[config.txt](https://github.com/jeffduda/NeuroBattery/files/598488/config.txt)

**Comment by Mageshwar** [comment]
Did someone find a solution to this problem? Please let me know. Thanks

**Comment by jeffduda** [comment]
A variety of fixes have been submitted to ANTs  and ANTsR to update these scripts. You will need to install the latest git commits of both. However based on your errors message it looks like the ANTs executable are not being found correctly so you'll need to make sure your PATH is set correctly
